In [1]:
import pandas as pd

In [2]:
pd.read_stata("/Users/arun/Desktop/SHRI documents/Tracking/raw data/data_barcodecheckin20Mar2023_raw.dta")

,_id,uuid,starttime,maintenance_numberid_in,nametimestamp,nametimestampformatted,__version__,instanceID,_xform_id_string,_uuid,_status,_submission_time,_submitted_by,start,v2nametimestamp,v2nametimestampformatted
0,142257897,6fb47b6f7023481289ab03113fb90d15,2022-02-18T05:02:30.207+05:30,B3001,2022-02-18T05:02:58.558+05:30,2022-02-18 05:02:58.558,v2YE2mpa69V2vXxYhFpsGa,uuid:12c2259d-8a74-49ee-a675-2e239c84ba4b,aLKzTfJAw5KKbtRxLUncwh,12c2259d-8a74-49ee-a675-2e239c84ba4b,submitted_via_web,2022-02-17T23:33:59,ranjitkumar,,,
1,142269499,6fb47b6f7023481289ab03113fb90d15,2022-02-18T10:01:05.151+05:30,B3002,2022-02-18T10:01:22.744+05:30,2022-02-18 10:01:22.744,v2YE2mpa69V2vXxYhFpsGa,uuid:08ef61fb-8503-4a76-bac9-681263bd838e,aLKzTfJAw5KKbtRxLUncwh,08ef61fb-8503-4a76-bac9-681263bd838e,submitted_via_web,2022-02-18T04:32:22,ranjitkumar,,,
2,142269501,6fb47b6f7023481289ab03113fb90d15,2022-02-18T10:01:36.865+05:30,B3003,2022-02-18T10:01:49.401+05:30,2022-02-18 10:01:49.401,v2YE2mpa69V2vXxYhFpsGa,uuid:cc242f13-6b89-4b95-b129-a7a32d94a9bb,aLKzTfJAw5KKbtRxLUncwh,cc242f13-6b89-4b95-b129-a7a32d94a9bb,submitted_via_web,2022-02-18T04:32:23,ranjitkumar,,,
3,142322019,6fb47b6f7023481289ab03113fb90d15,2022-02-18T16:16:15.383+05:30,B3003,2022-02-18T16:16:24.443+05:30,2022-02-18 16:16:24.443,v2YE2mpa69V2vXxYhFpsGa,uuid:0af7de73-7d82-4811-b286-ea6dc1f25510,aLKzTfJAw5KKbtRxLUncwh,0af7de73-7d82-4811-b286-ea6dc1f25510,submitted_via_web,2022-02-18T10:47:24,ranjitkumar,,,
4,142322035,6fb47b6f7023481289ab03113fb90d15,2022-02-18T16:16:32.457+05:30,B3001,2022-02-18T16:16:39.221+05:30,2022-02-18 16:16:39.221,v2YE2mpa69V2vXxYhFpsGa,uuid:7fe65569-e4f8-43d5-bc20-f683658c1b83,aLKzTfJAw5KKbtRxLUncwh,7fe65569-e4f8-43d5-bc20-f683658c1b83,submitted_via_web,2022-02-18T10:47:26,ranjitkumar,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9340,226452115,6fb47b6f7023481289ab03113fb90d15,,B3004,,,vEuUCHKvpSsYXPBVjGHZab,uuid:96e305a3-1fff-4de2-a1da-d8f5455cedc3,aLKzTfJAw5KKbtRxLUncwh,96e305a3-1fff-4de2-a1da-d8f5455cedc3,submitted_via_web,2023-03-20T13:29:52,ranjitkumar,2023-03-20T18:59:02.039+05:30,2023-03-20T18:59:07.193+05:30,2023-03-20 18:59:07.193
9341,226456689,6fb47b6f7023481289ab03113fb90d15,,N3004,,,vEuUCHKvpSsYXPBVjGHZab,uuid:c4a0d9a0-0e4b-4b84-8368-410e3e425ca7,aLKzTfJAw5KKbtRxLUncwh,c4a0d9a0-0e4b-4b84-8368-410e3e425ca7,submitted_via_web,2023-03-20T13:43:17,basgodanorth,2023-03-20T19:12:53.847+05:30,2023-03-20T19:13:00.790+05:30,2023-03-20 19:13:00.790
9342,226471587,6fb47b6f7023481289ab03113fb90d15,,P3004,,,vEuUCHKvpSsYXPBVjGHZab,uuid:029e3da3-4f23-4bdd-882d-76ff8611a158,aLKzTfJAw5KKbtRxLUncwh,029e3da3-4f23-4bdd-882d-76ff8611a158,submitted_via_web,2023-03-20T14:40:50,peterbar,2023-03-20T20:10:12.308+05:30,2023-03-20T20:10:39.368+05:30,2023-03-20 20:10:39.368
9343,226483151,6fb47b6f7023481289ab03113fb90d15,,2004,,,vEuUCHKvpSsYXPBVjGHZab,uuid:e9d75e8d-a685-4af3-912f-0edd2d369128,aLKzTfJAw5KKbtRxLUncwh,e9d75e8d-a685-4af3-912f-0edd2d369128,submitted_via_web,2023-03-20T15:29:43,shriindia,2023-03-20T20:55:19.544+05:30,2023-03-20T20:55:33.219+05:30,2023-03-20 20:55:33.219
9344,226496682,6fb47b6f7023481289ab03113fb90d15,,V1003,,,vEuUCHKvpSsYXPBVjGHZab,uuid:919cad20-887c-479b-b67a-4e8530f28324,aLKzTfJAw5KKbtRxLUncwh,919cad20-887c-479b-b67a-4e8530f28324,submitted_via_web,2023-03-20T16:22:16,vurahi,2023-03-20T21:51:03.116+05:30,2023-03-20T21:51:16.982+05:30,2023-03-20 21:51:16.982

In [3]:
pd.read_stata("/Users/arun/Downloads/data_barcodecheckin17Mar2023_clean.dta")

,userid,nametimestampformatted,facility,datetime_auto_day,date_auto,time_auto,yob,gender,date_enrollment,position,repeat_numberid,nametimestampformatted_in,instanceName,_submission_time
0,2001,2023-01-14 03:52:41.396,Dundibagh,2023-01-14 03:52:41.396,2023-01-14,1960-01-01 03:52:00,1992,Male,2021-09-30,Facility incharge and water seller,,,,
1,2001,2023-01-25 03:51:04.779,Dundibagh,2023-01-25 03:51:04.779,2023-01-25,1960-01-01 03:51:00,1992,Male,2021-09-30,Facility incharge and water seller,,,,
2,2001,2022-10-23 03:51:21.267,Dundibagh,2022-10-23 03:51:21.267,2022-10-23,1960-01-01 03:51:00,1992,Male,2021-09-30,Facility incharge and water seller,,,,
3,2001,2023-01-28 03:53:23.944,Dundibagh,2023-01-28 03:53:23.944,2023-01-28,1960-01-01 03:53:00,1992,Male,2021-09-30,Facility incharge and water seller,,,,
4,2001,2022-11-7 03:54:51.433,Dundibagh,2022-11-07 03:54:51.433,2022-11-07,1960-01-01 03:54:00,1992,Male,2021-09-30,Facility incharge and water seller,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10469,G1005,,Gomia,2022-02-09 13:07:00.000,2022-02-09,1960-01-01 13:07:00,2000,Male,2022-02-08,Data collection 2,G1005,2022-02-9 13:07:30.676,maintenance_checkin_G1005,2022-02-09T07:37:46
10470,G1005,,Gomia,2022-02-24 13:24:00.000,2022-02-24,1960-01-01 13:24:00,2000,Male,2022-02-08,Data collection 2,G1005,2022-02-24 13:24:07.359,maintenance_checkin_G1005,2022-02-24T07:54:26
10471,G1005,,Gomia,2022-02-20 14:01:00.000,2022-02-20,1960-01-01 14:01:00,2000,Male,2022-02-08,Data collection 2,G1005,2022-02-20 14:01:18.098,maintenance_checkin_G1005,2022-02-20T08:31:54
10472,G1005,,Gomia,2022-02-23 13:09:00.000,2022-02-23,1960-01-01 13:09:00,2000,Male,2022-02-08,Data collection 2,G1005,2022-02-23 13:09:52.838,maintenance_checkin_G1005,2022-02-23T07:40:03
10473,G1005,,Gomia,2022-02-16 13:03:00.000,2022-02-16,1960-01-01 13:03:00,2000,Male,2022-02-08,Data collection 2,G1005,2022-02-16 13:03:16.628,maintenance_checkin_G1005,2022-02-16T07:33:32