In [1]:
import pandas as pd

In [5]:
a = pd.read_stata("/Users/arun/Downloads/data_dailyissue06Apr2023_clean.dta")

In [4]:
pd.read_stata("/Users/arun/Downloads/dailyissue_06Apr2023_dashboard.dta")

,facility,issue,date_auto,shutdown,full_partial,num_hours
0,Azad Nagar,Plumbing - toilet tap,2023-01-28,,,
1,Azad Nagar,Technology - internet,2023-02-16,no,,
2,Azad Nagar,Supplies - harpic etc,2023-03-19,no,,
3,Azad Nagar,Electrical - boring,2023-03-22,no,,
4,Azad Nagar,Electrical - bulb,2023-04-05,no,,
5,Basgoda,Plumbing - pipe,2023-02-09,,,
6,Basgoda,Water filter,2023-02-10,,,
7,Basgoda,Electrical - wiring,2023-02-14,no,,
8,Basgoda,Electrical - boring,2023-02-17,no,,
9,Basgoda,Plumbing - basin tap,2023-03-19,no,,
10,Basgoda,Plumbing - basin tap,2023-03-22,no,,
11,Basgoda,Electrical - bulb,2023-04-05,no,,
12,Basgoda North,Plumbing - toilet tap,2023-02-11,no,,
13,Basgoda North,Plumbing - toilet tap,2023-03-25,no,,
14,Dundibagh,Technology - tablet,2023-01-25,,,
15,Dundibagh,Supplies - harpic etc,2023-01-31,,,
16,Dundibagh,Electrical - bulb,2023-01-31,,,
17,Dundibagh,Plumbing - toilet tap,2023-02-09,,,
18,Dundibagh,Infrastructure - gate,2023-02-27,no,,
19,Dundibagh,Plumbing - toilet tap,2023-03-24,no,,
20,Gomia,Electrical - wiring,2023-02-02,,,
21,Gomia,Technology - internet,2023-02-02,,,
22,Gomia,Electrical - wiring,2023-03-22,no,,
23,Peterbaar,Plumbing - toilet tap,2023-01-23,,,
24,Peterbaar,Plumbing - basin tap,2023-01-23,,,
25,Peterbaar,Urinal pipe,2023-01-23,,,
26,Peterbaar,Supplies - soap,2023-01-27,,,
27,Peterbaar,Supplies - soap,2023-01-29,,,
28,Peterbaar,Supplies - soap,2023-01-31,,,
29,Peterbaar,Supplies - soap,2023-02-02,,,
30,Peterbaar,Supplies - soap,2023-02-04,,,
31,Peterbaar,Supplies - soap,2023-02-18,no,,
32,Peterbaar,Electrical - bulb,2023-03-02,no,,
33,Peterbaar,Supplies - soap,2023-03-02,no,,
34,Peterbaar,Supplies - harpic etc,2023-03-02,no,,
35,Peterbaar,Supplies - soap,2023-03-14,no,,
36,Peterbaar,Technology - internet,2023-03-16,no,,
37,Peterbaar,Electrical - bulb,2023-03-17,yes,part day,1
38,Peterbaar,Electrical - wiring,2023-03-17,yes,part day,2
39,Peterbaar,Supplies - soap,2023-03-29,no,,
40,Peterbaar,Electrical - wiring,2023-04-04,no,,
41,Peterbaar,Electrical - switch,2023-04-04,no,,
42,Vurahi,Infrastructure - gate,2023-02-24,no,,
43,Vurahi,Plumbing - basin tap,2023-03-28,no,,

In [6]:
a

,facility,datetime_auto_day,shift_type,issue,date_auto,any_issue,shutdown,full_partial,num_hours
0,Azad Nagar,2023-01-19 13:58:48.576,1,,2023-01-19,0.0,,,
1,Azad Nagar,2023-01-19 19:46:09.024,2,,2023-01-19,0.0,,,
2,Azad Nagar,2023-01-20 13:01:37.152,1,,2023-01-20,0.0,,,
3,Azad Nagar,2023-01-20 19:21:43.680,2,,2023-01-20,0.0,,,
4,Azad Nagar,2023-01-21 12:28:27.520,1,,2023-01-21,0.0,,,
...,...,...,...,...,...,...,...,...,...
937,Vurahi,2023-04-03 21:08:30.848,2,,2023-04-03,0.0,,,
938,Vurahi,2023-04-04 09:29:04.256,2,,2023-04-04,0.0,,,
939,Vurahi,2023-04-05 09:50:31.424,1,,2023-04-05,0.0,,,
940,Vurahi,2023-04-06 09:54:30.016,1,,2023-04-06,0.0,,,
941,Vurahi,2023-04-06 21:31:21.984,2,,2023-04-06,0.0,,,

In [7]:
a.any_issue

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
937    0.0
938    0.0
939    0.0
940    0.0
941    0.0
Name: any_issue, Length: 942, dtype: float32

In [8]:
a.to_numpy()

array([['Azad Nagar', Timestamp('2023-01-19 13:58:48.576000'), '1', ...,
        '', '', ''],
       ['Azad Nagar', Timestamp('2023-01-19 19:46:09.024000'), '2', ...,
        '', '', ''],
       ['Azad Nagar', Timestamp('2023-01-20 13:01:37.152000'), '1', ...,
        '', '', ''],
       ...,
       ['Vurahi', Timestamp('2023-04-05 09:50:31.424000'), '1', ..., '',
        '', ''],
       ['Vurahi', Timestamp('2023-04-06 09:54:30.016000'), '1', ..., '',
        '', ''],
       ['Vurahi', Timestamp('2023-04-06 21:31:21.984000'), '2', ..., '',
        '', '']], dtype=object)

In [9]:
b = a.any_issue

In [10]:
b.to_numpy

<bound method IndexOpsMixin.to_numpy of 0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
937    0.0
938    0.0
939    0.0
940    0.0
941    0.0
Name: any_issue, Length: 942, dtype: float32>

In [11]:
a

,facility,datetime_auto_day,shift_type,issue,date_auto,any_issue,shutdown,full_partial,num_hours
0,Azad Nagar,2023-01-19 13:58:48.576,1,,2023-01-19,0.0,,,
1,Azad Nagar,2023-01-19 19:46:09.024,2,,2023-01-19,0.0,,,
2,Azad Nagar,2023-01-20 13:01:37.152,1,,2023-01-20,0.0,,,
3,Azad Nagar,2023-01-20 19:21:43.680,2,,2023-01-20,0.0,,,
4,Azad Nagar,2023-01-21 12:28:27.520,1,,2023-01-21,0.0,,,
...,...,...,...,...,...,...,...,...,...
937,Vurahi,2023-04-03 21:08:30.848,2,,2023-04-03,0.0,,,
938,Vurahi,2023-04-04 09:29:04.256,2,,2023-04-04,0.0,,,
939,Vurahi,2023-04-05 09:50:31.424,1,,2023-04-05,0.0,,,
940,Vurahi,2023-04-06 09:54:30.016,1,,2023-04-06,0.0,,,
941,Vurahi,2023-04-06 21:31:21.984,2,,2023-04-06,0.0,,,